# Generated by Django 5.2.3 on 2025-07-03 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Creditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=1000)),
                ("country", models.CharField(max_length=2)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Creditor Email"
                    ),
                ),
                ("iban", models.CharField(max_length=34, unique=True)),
                ("name", models.CharField(max_length=1000)),
                ("pcode", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecurringBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_information",
                    models.TextField(
                        help_text="Description for the bill (e.g., 'YouTube Premium 2025Q2')."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("BQuarterBegin", "BQuarterBegin"),
                            ("BQuarterEnd", "BQuarterEnd"),
                            ("BYearBegin", "BYearBegin"),
                            ("BYearEnd", "BYearEnd"),
                            ("BusinessDay", "BusinessDay"),
                            ("BusinessHour", "BusinessHour"),
                            ("BusinessMonthBegin", "BusinessMonthBegin"),
                            ("BusinessMonthEnd", "BusinessMonthEnd"),
                            ("CustomBusinessDay", "CustomBusinessDay"),
                            ("CustomBusinessHour", "CustomBusinessHour"),
                            ("CustomBusinessMonthBegin", "CustomBusinessMonthBegin"),
                            ("CustomBusinessMonthEnd", "CustomBusinessMonthEnd"),
                            ("Day", "Day"),
                            ("Easter", "Easter"),
                            ("FY5253", "FY5253"),
                            ("FY5253Quarter", "FY5253Quarter"),
                            ("LastWeekOfMonth", "LastWeekOfMonth"),
                            ("MonthBegin", "MonthBegin"),
                            ("MonthEnd", "MonthEnd"),
                            ("QuarterBegin", "QuarterBegin"),
                            ("QuarterEnd", "QuarterEnd"),
                            ("SemiMonthBegin", "SemiMonthBegin"),
                            ("SemiMonthEnd", "SemiMonthEnd"),
                            ("Tick", "Tick"),
                            ("Week", "Week"),
                            ("WeekOfMonth", "WeekOfMonth"),
                            ("YearBegin", "YearBegin"),
                            ("YearEnd", "YearEnd"),
                        ],
                        help_text="The Pandas DateOffset to use for scheduling",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "next_due_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="The next date a bill will be generated and due.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to pause generating new bills from this schedule.",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bills.contact"
                    ),
                ),
                (
                    "creditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bills.creditor"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_information",
                    models.TextField(
                        help_text="Description for the bill (e.g., 'YouTube Premium 2025Q2')."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_number",
                    models.CharField(db_index=True, max_length=27, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Generation"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bills.contact"
                    ),
                ),
                (
                    "creditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bills.creditor"
                    ),
                ),
                (
                    "recurring_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bills.recurringbill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
