# Generated by Django 5.2.3 on 2025-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringbill",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("BusinessDay", "BusinessDay"),
                    ("BusinessMonthBegin", "BusinessMonthBegin"),
                    ("BusinessMonthEnd", "BusinessMonthEnd"),
                    ("Easter", "Easter"),
                    ("LastWeekOfMonth", "LastWeekOfMonth"),
                    ("MonthBegin", "MonthBegin"),
                    ("MonthEnd", "MonthEnd"),
                    ("QuarterBegin", "QuarterBegin"),
                    ("QuarterEnd", "QuarterEnd"),
                    ("SemiMonthBegin", "SemiMonthBegin"),
                    ("SemiMonthEnd", "SemiMonthEnd"),
                    ("Week", "Week"),
                    ("WeekOfMonth", "WeekOfMonth"),
                    ("YearBegin", "YearBegin"),
                    ("YearEnd", "YearEnd"),
                ],
                help_text="The Pandas DateOffset to use for scheduling",
                max_length=50,
            ),
        ),
    ]
