# Generated by Django 5.2.3 on 2025-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0002_alter_recurringbill_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringbill",
            name="frequency_kwargs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object with keyword arguments for the offset (e.g., {'n': 2, 'normalize': True}).",
            ),
        ),
    ]
