# Generated by Django 5.2.3 on 2025-07-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_bill_currency_alter_bill_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='recurring_bill',
            field=models.ForeignKey(blank=True, help_text='Link back to the schedule that created this bill. If the schedule is deleted, this bill remains but is no longer linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.recurringbill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Unique RF-Creditor Reference for the bill.', max_length=27),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The next date a bill will be generated. Defaults to start_date.'),
        ),
    ]
