# Generated by Django 5.2.3 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0007_alter_bill_recurring_bill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="overdue_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="overdue_notification_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
