# Generated by Django 6.0.4 on 2026-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0008_bill_overdue_notification_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="reference_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="RF-Creditor reference for the bill.",
                max_length=27,
            ),
        ),
    ]
