# Generated by Django 6.0.4 on 2026-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0009_alter_bill_reference_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditor",
            name="house_num",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="creditor",
            name="street",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
    ]
