name: Build & Deploy Application to GHCR

on:
  push:
    branches:
      - main

env:
  APP_NAME: bills
  DOCKERFILE_PATH: Dockerfile
  DOCKER_IMAGE_NAME: ghcr.io/enucatl/bills

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Allows checking out code
      packages: write  # Allows pushing to GitHub Container Registry (ghcr.io)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Important: Fetches full history for git describe to work
          fetch-depth: 0 

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Get CARGO_PACKAGE_VERSION from git
        id: get_version
        run: |
          VERSION=$(git describe --long | sed 's/-/\./')
          echo "Detected CARGO_PACKAGE_VERSION: $VERSION"
          echo "CARGO_PACKAGE_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Run cargo test
        run: cargo test --verbose

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}          # The GitHub Actions bot username
          password: ${{ secrets.GITHUB_TOKEN }} # The special token for repo/GHCR access

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.CARGO_PACKAGE_VERSION }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
          build-args: |
            CARGO_PACKAGE_VERSION=${{ steps.get_version.outputs.CARGO_PACKAGE_VERSION }}

      - name: Trigger Portainer Redeploy
        # This step runs only if the build and push was successful.
        # It sends a POST request to a Portainer webhook, which triggers
        # Portainer to pull the new :latest image and redeploy the service.
        if: success()
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
