name: Build & Deploy Application to GHCR

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      meta_tags: ${{ steps.tags.outputs.meta_tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install project dependencies with uv
        run: uv sync --all-extras --dev

      - name: Get Application Version from setuptools-git-versioning
        id: get_version
        run: |
          VERSION=$(uv run setuptools-git-versioning)
          echo "Detected VERSION: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Run Django tests
        run: DATABASE_URL="sqlite:///:memory:" uv run python src/send_bills/manage.py test bills api

      - name: Generate Docker Tags
        id: tags
        shell: bash
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          set -euo pipefail

          BASE_VERSION=$(echo "${VERSION}" | cut -d'+' -f1)
          IFS='.' read -r -a V_PARTS <<< "$BASE_VERSION"
          V_MAJOR=${V_PARTS[0]}
          V_MINOR=${V_PARTS[1]}

          TAG_LIST=$( (
          echo "latest"
          echo "$BASE_VERSION"
          echo "$V_MAJOR.$V_MINOR"
          echo "$V_MAJOR"
          ) | sort -u )

          {
            echo "meta_tags<<EOF"
            for TAG in $TAG_LIST; do
              echo "type=raw,value=${TAG}"
            done
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  docker:
    needs: test
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    uses: Enucatl/docker-compose-security-baseline/.github/workflows/docker-ci.yml@main
    with:
      image_name: ghcr.io/enucatl/bills
      version: ${{ needs.test.outputs.version }}
      meta_tags: ${{ needs.test.outputs.meta_tags }}
      context: .
      dockerfile: Dockerfile
      platforms: linux/amd64
      push: true
      build_args: |
        VERSION=${{ needs.test.outputs.version }}
    secrets: inherit
